### ISSUE TITLE
【泰國】線上註冊-在登入時若無該帳號，請 alert 錯誤訊息

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#102]
目前登入時若資料庫查無該帳號，畫面會跳轉但無提示訊息，
請麻煩若查無帳號時 alert 以下錯誤訊息 "Invalid E-mail or password."

**Comment by mattiiichen** [comment]
改修正


<img width="561" alt="2018-10-09 12 02 53" src="https://user-images.githubusercontent.com/18495618/46646191-54fd2800-cbbb-11e8-9983-b39e0db3fb68.png">

**Comment by minzyliu** [comment]
done
