### ISSUE TITLE
【BUG】選擇payment之後，出現error

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#104]
環境:demo
頁面:payment_process
異常說明:
![2](https://user-images.githubusercontent.com/42991376/46198780-d9d87e00-c33f-11e8-8096-6cdeec752609.PNG)
![3](https://user-images.githubusercontent.com/42991376/46198781-da711480-c33f-11e8-9d59-3d1296408ec4.PNG)
![4](https://user-images.githubusercontent.com/42991376/46198782-da711480-c33f-11e8-8bba-a8522ee29510.PNG)

**Comment by ringo636** [comment]
我是在選擇付款方式後出現以下錯誤畫面
![2018-10-03 4 05 08](https://user-images.githubusercontent.com/6264391/46397930-306dff80-c726-11e8-9043-63d41a3baf22.png)

**Comment by minzyliu** [comment]
done
