### ISSUE TITLE
【Orc】RMMS新增商品時出現「轉換失敗」的視窗

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#121]
環境：drink
異常說明：
新增商品的時候出現下方畫面
![1](https://user-images.githubusercontent.com/42991376/46283525-2d98d080-c5a7-11e8-8968-3f20f42caed6.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
2018/10/02 11:45 實測 還有此問題

**Comment by jerrymds** [comment]
有哪些設定才會產生此問題?

**Comment by minzyliu** [comment]
fixed
