### ISSUE TITLE
【Orc】點修改商品，商品資料欄位空白

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#122]
環境：drink
異常說明：
修改商品 milk tea，進入畫面欄位空白
![1](https://user-images.githubusercontent.com/42991376/46283631-78b2e380-c5a7-11e8-8fd6-0314e1dc9d7c.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
