### ISSUE TITLE
【Orc】點查詢商品，彈出異常畫面

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#123]
環境:drink
異常說明:
點選查詢商品，出現以下畫面
![1](https://user-images.githubusercontent.com/42991376/46283704-c0d20600-c5a7-11e8-810a-dcbb5fa29485.PNG)

**Comment by minzyliu** [comment]
將商品下架，也出現此畫面
(但商品是可以成功下架的)

**Comment by minzyliu** [comment]
上架/下架/編輯的頁面，按下查詢按鈕都有出現此error

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
