### ISSUE TITLE
【Orc】新增供應商資料彈出異常畫面

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#125]
環境: drink
異常說明:
輸入以下資料
[結果]彈出下方錯誤
![1](https://user-images.githubusercontent.com/42991376/46284063-0fcc6b00-c5a9-11e8-87ba-c61a9b587b5c.PNG)
![2](https://user-images.githubusercontent.com/42991376/46284064-10650180-c5a9-11e8-86e5-d6384fd7eb25.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
