### ISSUE TITLE
【Orc】新增會員，第一次無法查詢到剛新增的

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#126]
環境: drink
異常說明:
新增會員 coco
成功儲存
點選side bar的查詢會員
[結果1] 彈出 #123 的問題

[結果2] 把異常視窗關閉後，沒有出現剛剛建立的會員資料
需要切換到查詢會員第二頁，再切換回來第一頁，才會出現

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
