### ISSUE TITLE
【Orc】新增預購單-搜尋會員時，出現null

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#128]
環境: drink
異常說明:
搜尋會員，出現以下畫面
![1](https://user-images.githubusercontent.com/42991376/46284415-4a82d300-c5aa-11e8-852b-537b96260619.PNG)

**Comment by minzyliu** [comment]
新增儲值金也有這個異常

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
