### ISSUE TITLE
【Orc】快捷link的連結，記得更換

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#129]
環境: drink
說明:
快捷link，到時候需要更換
目前點了，連結到haproxy這個pos link
![1](https://user-images.githubusercontent.com/42991376/46284788-bc0f5100-c5ab-11e8-8838-f9b4285a3319.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
