### ISSUE TITLE
【點數】商城-審核積分商品

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#13]
PEM管理員，在商城後台審核供應商上架的積分商品
積分商品定義: https://github.com/ringo636/Tib/issues/12

積分商品審核流程:

1. PEM管理員Login (https://shop3.tibbuy.net/pemall/admins)
2. 進入路徑:商品-->待審商品
3. 開始審核商品
 審核通過:商品到上架區
 審核不通過:商品停留在待審區
 備註:RMMS的商品管理可以看到商品審核的狀態

**Comment by minzyliu** [comment]
Dateline: 2018/10/8

**Comment by alen-li** [comment]
原主圖(是,否)欄改成顯示點數。

**Comment by minzyliu** [comment]
done
