### ISSUE TITLE
【Orc】部分沒有翻譯成英文

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#130]
環境: drink
異常說明:
需翻譯成英文
business tax 
doctor 
sales
![1](https://user-images.githubusercontent.com/42991376/46284959-48217880-c5ac-11e8-8ba5-36f831ff446c.PNG)

**Comment by ringo636** [comment]
我看到的是功能部分皆為中文，補充上來給阿華參考
![2018-10-02 10 57 47](https://user-images.githubusercontent.com/6264391/46327011-19e67c00-c632-11e8-86bd-44440335fe1b.png)

**Comment by minzyliu** [comment]
done
