### ISSUE TITLE
【Orc】環境設定，無法成功儲存

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#131]
環境: drink
異常說明:
進入環境設定
輸入discount
[結果] 無法儲存

**Comment by alen-li** [comment]
請忘記環境設定，現在改成搭配systemid全公用版的了，admin單一設定並不代表甚麼，跟個別帳號登入取得值無關。

**Comment by minzyliu** [comment]
結語
pos語言by帳號設定，每個帳號可以設定不同的語言
