### ISSUE TITLE
【Orc】POS 的選擇醫師業務的部分在行動裝置跑版

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#139]
發現在行動裝置的部分會跑版，
檢查了一下可能是程式在設定迴圈時，沒有把`<div class="row">`這一段加進去
![2018-10-02 11 29 11](https://user-images.githubusercontent.com/6264391/46327864-7fd50280-c636-11e8-878b-1b7add1ee32c.png)
請把這段拖進迴圈裡就可以囉～謝謝！

跑版畫面：
![2018-10-02 11 30 58](https://user-images.githubusercontent.com/6264391/46327895-b3179180-c636-11e8-8a02-af9fbba3ee90.png)

**Comment by minzyliu** [comment]
done
