### ISSUE TITLE
【Orc】RMMS-新增進貨單出現 錯誤提醒

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#141]
異常說明:
1.Purchase date 選擇今天
2.輸入兩個商品
3.儲存
[結果] 彈出下面ERROR訊息
![1](https://user-images.githubusercontent.com/42991376/46330366-38a23e00-c645-11e8-9bcc-33c8f3609121.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
