### ISSUE TITLE
【Orc】RMMS-銷貨明細表-付款方式出現中文

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#142]
異常說明:
銷貨明細表的付款方式顯示中文
![1](https://user-images.githubusercontent.com/42991376/46330468-a9495a80-c645-11e8-867d-c36fd9f2224e.PNG)

**Comment by jerrymds** [comment]
這是 POS 打過來的資料，應該是之前還沒改改英文時打的資料

**Comment by jerrymds** [comment]
已將資料庫資料改成英文了

**Comment by minzyliu** [comment]
done
