### ISSUE TITLE
【Orc】銷貨單(Sales order)點選退貨(Return)後會出現Captcha驗證失敗

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#152]
網址：
http://192.168.3.222/rmms/order/index

點選退貨(Return)後會出現是否確定要退貨，點選OK後會出現Captcha驗證失敗視窗
![2018-10-02 2 03 53](https://user-images.githubusercontent.com/6264391/46331823-3abbcb00-c64c-11e8-9215-6e83473042bc.png)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
done
