### ISSUE TITLE
【Orc】在新增庫存調整單(Add inventory adjustment)輸入商品名稱後，不會出現下拉選單

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#154]
其他功能這個欄位在輸入商品名稱後會有 auto complete 出現下拉選單
但在新增庫存調整單(Add inventory adjustment)沒有出現
理論上應該要出現 MILK TEA 讓我選

畫面截圖：
![2018-10-02 2 20 26](https://user-images.githubusercontent.com/6264391/46332354-bae33000-c64e-11e8-9be1-08e74eac9425.png)

**Comment by jerrymds** [comment]
MILK TEA 是不扣庫存商品，所以不會出現在庫存調整單的搜尋中

**Comment by minzyliu** [comment]
了解，庫存調整單與盤點單的商品搜尋，只會出現有庫存的商品
