### ISSUE TITLE
【Orc】泰國RMMS使用手冊部分請修改為英文版本

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#157]
目前泰國RMMS使用手冊在 Menu 的顯示如下圖
![2018-10-02 2 49 09](https://user-images.githubusercontent.com/6264391/46333911-b91c6b00-c654-11e8-880e-277044b3ae44.png)
需要做以下修改：
1. 只留下一個項目 "Download user guide"
2. 改為連至以下pdf
(麻煩 Olivia 幫忙補上 pdf)

**Comment by jerrymds** [comment]
已完成

**Comment by minzyliu** [comment]
done
