### ISSUE TITLE
【Orc】RMMS-新增進貨單搜尋商品名稱出現null

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#162]
異常說明:
1. 新增進貨單
2. 搜尋商品名稱
3. 輸入hello
4. 出現hello birthday cake 
[結果] 商品名稱後方出現null
![default](https://user-images.githubusercontent.com/42991376/46449846-be96c400-c7c0-11e8-94e0-2ec06e96e06d.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
done
