### ISSUE TITLE
【Orc】RMMS-已建立的進貨單，沒有出現在查詢進貨單

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#163]
異常說明:
1.建立的進貨單
2.供應商名稱 Vegan food
3.日期 2018/10/04
[結果] 沒有出現在 查詢進貨單

**Comment by jerrymds** [comment]
沒有看到 Vegan food 這個供應商
但我建立進貨單後是有出現在查詢進貨單裡

**Comment by minzyliu** [comment]
done
