### ISSUE TITLE
【Orc】RMMS-查進貨單，arrival date選擇9/26，出現error

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#164]
異常說明: 
查詢進貨單
1. arrival date  選擇2018/9/26
2. 按下查詢
[結果] 出現以下畫面
![1](https://user-images.githubusercontent.com/42991376/46449988-7f1ca780-c7c1-11e8-98c6-0200a4831b40.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
