### ISSUE TITLE
【Orc】RMMS-庫存數量錯誤

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#165]
異常說明:
1. 新增商品 hello birthday cake
2. 新增進貨單 10個

[結果] 查詢庫存的時候，目前庫存是20個
![default](https://user-images.githubusercontent.com/42991376/46450086-13870a00-c7c2-11e8-9b39-ab0f2152c2bd.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
