### ISSUE TITLE
【Orc】RMMS-新增進貨單儲存後彈出error

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#166]
異常說明:
1. 新增進貨單
2. 選擇供應商 starbucks
3. 輸入商品 fruit cake
4. 數量10
5. 儲存
[結果] 出現以下畫面
![1](https://user-images.githubusercontent.com/42991376/46450270-0880a980-c7c3-11e8-8562-3823169e0a26.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
done
