### ISSUE TITLE
【Orc】RMMS-新增調撥單搜尋商品，商品名稱有null

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#167]
異常說明:
1. 新增調撥單
2. 搜尋商品 fruit cake

[結果] 商品名稱出現null
![1](https://user-images.githubusercontent.com/42991376/46450806-d6247b80-c7c5-11e8-8a35-565e62a42cc8.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
done
