### ISSUE TITLE
【Orc】RMMS-「新增進貨單」的供應商欄位與「查詢供應商」資料不符合

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#168]
異常說明：
查詢供應商的清單 & 新增進貨單的供應商選單，資料不吻合

//新增進貨單
![1](https://user-images.githubusercontent.com/42991376/46451315-2dc3e680-c7c8-11e8-92b8-b464ed125d16.PNG)

//查詢供應商
![2](https://user-images.githubusercontent.com/42991376/46451322-387e7b80-c7c8-11e8-977b-44dc67c7e5bb.PNG)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
fixed
