### ISSUE TITLE
【線上註冊】註冊成功後，無法登入

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#183]
異常說明:
成功註冊並結帳之後
在sign in 的畫面輸入帳號與密碼後，沒有反應
[預期結果] 可以登入並進入會員頁
![1](https://user-images.githubusercontent.com/42991376/46593054-e3f63b80-cafa-11e8-85e6-d17d18ba0e44.PNG)

**Comment by mattiiichen** [comment]
已修正，登入後直接導向會員中心

**Comment by minzyliu** [comment]
done
