### ISSUE TITLE
【PEM】商城後台-待處理訂單無法篩選出訂單

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#184]
異常說明:
訂單狀態選擇「全部」，篩選不出訂單
需要選擇等待付款才能篩選出來
![1](https://user-images.githubusercontent.com/42991376/46598576-2a599380-cb17-11e8-89ab-32501e1baabf.PNG)

**Comment by alen-li** [comment]
bug. fix.

**Comment by minzyliu** [comment]
done
