### ISSUE TITLE
【泰國】刪除分店的提醒視窗需翻譯

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#186]
需求:
以下文字需翻譯 
位置:
查詢分店> 刪除分店時會彈出的視窗

![1](https://user-images.githubusercontent.com/42991376/46680278-4fcfc580-cc1b-11e8-9dbe-5883e35604ae.PNG)

**Comment by jerrymds** [comment]
![default](https://user-images.githubusercontent.com/15310517/46778155-f19f0180-cd44-11e8-9456-7ce92eedef96.png)
有喔! 你檢查一下是不是瀏覽器的語言沒設定

**Comment by minzyliu** [comment]
已補充翻譯
