### ISSUE TITLE
【泰國】RMMS-查詢分店，分店無法刪除

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#188]
環境: pets / th
異常說明:
1.新增分店
2.按下儲存，沒有反應
3. 再按一下儲存
4. 查詢分店處，出現兩個相同名稱的分店
5. 刪除其中一個
[結果] 無法刪除，彈出 該分店已被使用的視窗

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
done
