### ISSUE TITLE
【PEM】RMMS-firefox新增商品無法上傳圖片

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#191]
環境: china, pemall
異常說明:
1. pemall1/ pemall1@168
2. 新增商品時，上傳圖片按鈕沒有反應

**Comment by jerrymds** [comment]
![default](https://user-images.githubusercontent.com/15310517/46858480-f5fb1580-ce3d-11e8-86ec-dfcfdbaae06d.png)
我的可以耶

**Comment by minzyliu** [comment]
done
