### ISSUE TITLE
【PEM】商城-更新商品圖片APP上已顯示，但WEB端沒有顯示商品圖

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#193]
環境: China,pemall
異常說明:
1. 商品  85ba1fa2-591c-492d-9744-569b4de3c4d5
2. RMMS新增商品圖片
3. 到商城後台按下 更新商品、同步商品
[結果] app上有顯示，web沒有顯示
![1](https://user-images.githubusercontent.com/42991376/46778210-4cd0f400-cd45-11e8-9208-964bca35662a.PNG)

**Comment by alen-li** [comment]
有喔，WEB有顯示，所以問題是??

**Comment by minzyliu** [comment]
那應該是暫存的關係
