### ISSUE TITLE
【Orc】POS-使用議價打到RMMS顯示Undefined

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#202]
環境: retail / th
登入帳號: retail
訂單編號: Aws_443D985979218A96B6770F8A4E3CA8F0
異常說明:
使用議價功能
[結果] 後台查詢銷售單顯示undefined
![default](https://user-images.githubusercontent.com/42991376/46865044-b688f500-ce4e-11e8-8e2c-4b3a40df5d39.png)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
done
