### ISSUE TITLE
【Orc】RMMS-退單需要翻譯成英文

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#203]
環境: retail /th
帳號: retail / retail@168
異常說明:
查詢退貨單，「退單」要改成Return
![default](https://user-images.githubusercontent.com/42991376/46865715-154f6e00-ce51-11e8-8af7-79c36413c90b.png)

**Comment by jerrymds** [comment]
Remarks 是 POS 打過來的
原本退單就有被退的訂單編號
已請阿華拿掉 Remarks 的資訊不用打過來

**Comment by minzyliu** [comment]
done
