### ISSUE TITLE
【Orc】RMMS-時間的英文顯示有誤

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#205]
環境: retail / th
異常說明:
下午4:00 顯示4h
[預計結果] 應該顯示 16:00 或 4:00pm 
![default](https://user-images.githubusercontent.com/42991376/46865926-eb4a7b80-ce51-11e8-8ebc-31bfbaff2ff5.png)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
done
早上顯示 am
下午顯示 pm
