### ISSUE TITLE
【Orc】RMMS-系統設定保留項目

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#206]
需求:
泰國的系統設定，須開放給店家使用的項目(黃底) 
//其他的隱藏//
![default](https://user-images.githubusercontent.com/42991376/46925626-60d76700-d05f-11e8-9674-bac61e0cb30d.png)

翻譯:
幣別 Currency
會員等級 Member rating
商品規格 Specification

**Comment by jerrymds** [comment]
已完成

**Comment by minzyliu** [comment]
done
