### ISSUE TITLE
【PEM】RMMS-新增使用者的分店，改為櫃位

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#209]
環境: 中國
異常說明:
分店改為 櫃位
![default](https://user-images.githubusercontent.com/42991376/46926972-c7f81a00-d065-11e8-808b-ebe7190d0132.png)

**Comment by jerrymds** [comment]
已修正

**Comment by minzyliu** [comment]
![default](https://user-images.githubusercontent.com/42991376/46987649-b7a87380-d127-11e8-824d-f1366c6298ac.png)
done
