### ISSUE TITLE
【PEM】近期消息的 T 移除

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#221]
需求:
近期消息的T 移除，用空格 區隔 日期與時間

![s__29884547](https://user-images.githubusercontent.com/42991376/46946994-fc8ec480-d0ab-11e8-9bf4-faa71e614653.jpg)

**Comment by alen-li** [comment]
麻煩jerry協助，我這邊是資料庫除非改型態不然沒法調。

**Comment by minzyliu** [comment]
done
