### ISSUE TITLE
【Orc】POS-在RMMS新增會員，POS搜尋不到

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#222]
環境: retail / th
會員: winnie
瀏覽器: CHROME
異常說明:
1. 在rmms新增會員 winnie
2. 到pos按下sync customer
[結果]
sync 成功，可是搜尋不到該名會員

![default](https://user-images.githubusercontent.com/42991376/46988153-df004000-d129-11e8-8f8d-ee2be5992621.png)

![default](https://user-images.githubusercontent.com/42991376/46988159-e6274e00-d129-11e8-9d8e-73b9a0a78fa0.png)

**Comment by minzyliu** [comment]
done

**Comment by alen-li** [comment]
有喔，請注意大小寫。
Oracle設定區分大小寫，所以這部分需配合他。
