### ISSUE TITLE
【Orc】POS-商品下架，讓該分類無商品，但分類還是會出現在POS

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#226]
環境: coffee/ th
狀況說明:
1. 將分類"SOFT DRINK"裡面的商品下架
2. 到POS 按下 SYNC PRODUCT
[結果] 分類還是會出現在POS，但裡面沒有商品

[提問] 是否分類裡有上架商品的才會顯示在POS

**Comment by alen-li** [comment]
Bug, FIX.

**Comment by minzyliu** [comment]
done
