### ISSUE TITLE
【管理後台】註冊帳號，但是沒有驗證，沒出現在後台

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#227]
環境: shop3
帳號: minzy1@tibtrade.net
異常說明:
1. 點選註冊
2. 輸入帳號等資料
3. 按下一步
4. 進到 請去收驗證信的頁面
5. 然後沒有去驗證
[結果] 後台沒有收到該帳號的註冊資訊
[預期結果] 後台可查到該帳號，狀態inactive

**Comment by mattiiichen** [comment]
已修正

**Comment by mattiiichen** [comment]
已修正
