### ISSUE TITLE
【PEM】商品詳情頁-TOP的箭頭，點選後箭頭會不見

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#235]
環境: https://shop3.tibbuy.net/pemall/peapp/product/306a5c73-2698-405c-98df-733ac537f7b2
異常說明:
1. 游標點選TOP
2. TOP的按鈕，會變成藍底
[結果] 箭頭符號沒有出現
[預期結果] 藍底，箭頭符號白色

**Comment by ringo636** [comment]
https://shop3.tibbuy.net/pemall/theme/pemall/css/a000.css
這隻CSS裡面有一段
`
.scroll-to-top:hover, .scroll-to-top:focus {
    background-color: #5554a3;
    color: #ffffff;
}
`
麻煩改成
`
.scroll-to-top:hover, .scroll-to-top:focus {
    background-color: #5554a3;
    color: #ffffff !important;
}
`
應該就可以囉
