### ISSUE TITLE
【阿原】商城-註冊會員需增加簡訊認證輸入頁面、重發驗證碼按鈕

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#247]
定義:

1.商城會員註冊，帳號是手機號碼
2.輸入手機號碼後，需發送驗證簡訊，並輸入驗證碼後
3.再設定密碼，最後再送出

需求:
1.會員註冊頁，增加輸入簡訊驗證碼欄位
2.會員註冊頁，增加「重發認證信」按鈕
3.會員註冊輸入驗證碼後，才設定密碼

參考資料:
EZTABLE
UBER

**Comment by ringo636** [comment]
memo: 改好以後排在#244後面給阿華
