### ISSUE TITLE
【PEM】RMMS-商鋪折價券設定後台

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#268]
定義:
1. 功能名稱: 商鋪折價券
2. 每個會員都能領取、使用
3. 一張訂單，只能使用一張商鋪折價券
4. 一間店鋪可以設定很多張折價券
5. 券的開始帶的時間是 00:00:00 / 結束帶的時間是 23:59:59
6. 商鋪只能看到屬於自己商鋪的折價券、PEM管理員可以看到所有的折價券
7. 查詢商鋪折價券排序: 最新->最舊
8. API 設計詳見 (      )

需求:
1. 新增商鋪折價券: 
商鋪名稱: 系統依照登入帳號帶入
須滿金額: 填入數字
折抵金額: 填入數字
開始日期: 日曆選擇器
結束日期: 日曆選擇器
是否啟用: 是/否 
![default](https://user-images.githubusercontent.com/42991376/47600587-23c38b00-d9f6-11e8-9219-59894107fe82.png)

2. 查詢商鋪折價券: (查詢商鋪折價券顯示的欄位)
商鋪名稱
須滿金額
折抵金額
開始日期
結束日期
是否啟用
操作:  停用/刪除
> 已經開始的: 只能停用
> 尚未開始的: 可以刪除

**Comment by kiwi-tcliu** [comment]
done , 更新於api.v120一併更新
