### ISSUE TITLE
【點數】畫面-積分商品詳細頁

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#4]
將以下截圖畫面中金額的部分改為"點數"的顯示方式即可
![2018-09-07 4 51 40](https://user-images.githubusercontent.com/6264391/45208945-64d4d400-b2be-11e8-90c0-2f533169e28d.png)
商品詳細頁網址
https://shop3.tibbuy.net/pemall/peapp/product/eda08ac3-4660-4484-808a-7101b9fc0858

**Comment by ringo636** [comment]
已修改為以下樣式：
![2018-09-28 2 27 08](https://user-images.githubusercontent.com/6264391/46191601-b9ea8f80-c32a-11e8-82ce-bfdb3e9425ce.png)

emma/root/[商城]%20PEM版本/a000-product-pem.html

**Comment by alen-li** [comment]
已套用，請參考此頁
http://shop3.tibbuy.net/pemall/peapp/product/e92fdf33-b340-4b38-812a-dec959259079

**Comment by minzyliu** [comment]
done
