### ISSUE TITLE
[阿原]POS-新增會員，是否直接顯示道會員詳細資料頁面

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#411]
疑問說明:
舊的POS畫面，新增會員，會直接選擇會員
![default](https://user-images.githubusercontent.com/42991376/48658656-68d05f80-ea80-11e8-8f2e-2e67388c7877.png)

新的POS，是否在POS新增完會員，也直接選擇會員、顯示會員頁
![default](https://user-images.githubusercontent.com/42991376/48658637-1727d500-ea80-11e8-9932-5cc2b5a27c59.png)
![default](https://user-images.githubusercontent.com/42991376/48658662-95847700-ea80-11e8-8af7-c7d4a318b99e.png)

**Comment by ringo636** [comment]
現在新增會員已經會自動選取該會員，至於預設tab選在會員，這個我另外開一個issue
