### ISSUE TITLE
【RMMS】系統參數可設定稅率

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#43]
需求:
RMMS的系統參數設定，可填寫稅率的% 
RMMS稅率的部分主要影響「外加稅」，會把稅率的資訊打給POS計算

**Comment by jerrymds** [comment]
RMMS 參數：
營業稅=> SysId: Tax1, SysValue: Busness Tax, ExtValue: 5%
其它稅=> SysId: Tax2, SysValue: Other Tax, ExtValue: 7%
服務費=> SysId: ServiceFee, SysValue: Service fee, ExtValue: 10%

TibAdmin 參數：
SysArgumetns : "ArgId": "Boolen", "ArgType": "TaxRequired", "ArgTypeName": "商店應稅"

商品：
加欄位 TaxType (1: 內含, 2: 外加, 3: 免稅)

**Comment by alen-li** [comment]
配合套用

**Comment by minzyliu** [comment]
done
