### ISSUE TITLE
【阿原】行銷模組-紅配綠無法設定紅、綠的商品

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#437]
環境:demo
異常說明:
1. 無法設定紅、綠商品
2. 選擇商品的「不限」需隱藏
3. 「須滿多少金額」的欄位需移除

![default](https://user-images.githubusercontent.com/42991376/48674420-eed6ce00-eb86-11e8-9d45-fee683f921d1.png)
![default](https://user-images.githubusercontent.com/42991376/48674487-de732300-eb87-11e8-9948-fef71e814af7.png)

**Comment by ringo636** [comment]
已確認解決
