### ISSUE TITLE
【阿原】行銷模組-加價購金額欄位需輸入加購金額

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#438]
環境:demo
異常說明:
1. 單位，改成 加購金額，且只能輸入金額
2. 選擇加購商品只能夠單選
3. 選擇加購商品，「不限」的選項需隱藏
4. 最多可使用量，需更名為 加價購商品數量
5. 涵蓋/贈送商品，需移除此項目，已重複選擇商品功能
![default](https://user-images.githubusercontent.com/42991376/48674647-71608d00-eb89-11e8-98c3-e1a546b7d17c.png)
![default](https://user-images.githubusercontent.com/42991376/48674675-bbe20980-eb89-11e8-8675-6061fb5acaf4.png)

**Comment by alen-li** [comment]
這樣改會與商城加價購的設定相異，慎思

**Comment by kiwi-tcliu** [comment]
done, 同行銷模組上線
