### ISSUE TITLE
[阿原] RMMS-商城來的訂單，展開明細沒有顯示內容

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#483]
環境:DEMO
訂單編號:demo_1122000132 	
異常說明:
商城的訂單無法顯示商品明細

demo_1122000132 |  
-- | --
![default](https://user-images.githubusercontent.com/42991376/48879202-ac8ee480-ee45-11e8-8d32-19a6eb3ed2bd.png)

**Comment by jerrymds** [comment]
資料庫沒有明細
請阿華幫忙看

**Comment by minzyliu** [comment]
2019/1/11 fixed
