### ISSUE TITLE
[阿原] 出單-異常與須補欄位

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#492]
異常:
1. 發票金額與明細金額不同
2. 統編變更後，印出來還是舊的統編
3. 訂單編號後三碼與訂單相同，前綴的值不確定是否與要帶入鼎新的資料相同

需求:
1. 補上銷售員欄位，值帶入員編

**Comment by alen-li** [comment]
1.金額FIX，請更新程式
2.統編帶入的是字軌匯入的companyNo
3....XD
