### ISSUE TITLE
[阿原] 行銷模組邏輯

### ISSUE THREAD

**Issue by kiwi-tcliu** [ringo636/Tib#520]
![2018-11-28 5 54 20](https://user-images.githubusercontent.com/44760867/49143775-b5e0eb00-f336-11e8-91e9-03dc212bf6f0.png)
1.  折扣順序按照表格，最後計算為滿額贈
2. 滿額贈只能有一項，如果多點選，會跳出alert
3. 生日優惠，由於可以由使用者選時間，故做按鈕讓銷售員點選，有取得生日優惠及取消生日優惠兩個按鈕，在促銷顯示
4. 由於促販組會有除不盡的狀態，所以按比例分攤，但最後一項商品用減的
5. 商城的會員禮跟POS不掛鉤

**Comment by alen-li** [comment]
配合調整完畢

**Comment by kiwi-tcliu** [comment]
done
