### ISSUE TITLE
tibadmin 設定分店只能查看自己銷售單，但分店還是能查到所有店的

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#533]
正式環境

設定分店只能查自己銷售單，但登入分店帳號，還是可以看到所有分店的

**Comment by minzyliu** [comment]
目前查詢銷售單，只看到天光門市、沒有分店的
但出貨倉的下拉選單，會出現所有分店

**Comment by kiwi-tcliu** [comment]
https://github.com/ringo636/Tib/issues/548
權限設定詳見此issue

**Comment by kiwi-tcliu** [comment]
https://github.com/ringo636/Tib/issues/548
權限設定詳見此issue
