### ISSUE TITLE
[POS] 用手戳A商品按鈕，在用掃描器掃描B商品後，會一直出現A商品在購物清單

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#597]
環境: 正式環境
異常說明:
1. 手按POS右側商品按鈕  (水月碟禮盒)
2. 再用掃描器 掃商品BARCODE ( 0076000009)
[結果] 購物清單會出現 水月碟禮盒，不會出現 0076000009

**Comment by alen-li** [comment]
經驗證為 touch panel 的問題。scaner event被劫走了

**Comment by kiwi-tcliu** [comment]
處理方式：如果需要同時並行，點完商品後，請銷售人員點回搜尋input

done
