### ISSUE TITLE
【阿原】商城加入的會員沒有帶所屬分店，會員編號也沒有帶分店別

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#598]
環境:正式環境
會員: 劉旻芝
異常說明：
1. 從商成加入會員，會員編號前綴碼沒有帶倉別
2. 會員所屬分店空白
3. 手機號碼填到電話的欄位

**Comment by alen-li** [comment]
請提供異常的會員帳號或線索，以利釐清是前端還是後端的問題。

**Comment by minzyliu** [comment]
重複開票
