### ISSUE TITLE
【阿原】API-確認新增進貨單是否有重複寫入進貨單

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#621]
環境: 正式
異常說明;
以下這兩張進貨單的內容是重複的，需協助確認API LOG
是BUG，還是昶捷重複打兩次
201812100001
201812100003
![2018-12-10 9 17 01](https://user-images.githubusercontent.com/42991376/49735147-5d5c0700-fcc1-11e8-99c9-754e8aea66a5.png)
![messageimage_1544447960492](https://user-images.githubusercontent.com/42991376/49735149-5f25ca80-fcc1-11e8-95c6-846c52520cce.jpg)

**Comment by ringo636** [comment]
已確認應是昶捷重複打了
