### ISSUE TITLE
[阿原] 會員吳國卿的資料一直會被改成錯的

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#631]
會員姓名:吳oo
生日: 1900/08/00
手機:0952926599

該會員註冊並登入商城後，發現會員基本資料帶的是他的朋友陳婉如的名字，於是阿原的人進入RMMS幫他修改資料，該會員也再度進入商城查詢會員基本資料，有修改成吳國卿了，但過了一陣子再看又會變成陳婉如，此狀況大約重複發生三次
藥再麻煩確認是什麼原因造成，謝謝！

**Comment by kiwi-tcliu** [comment]
[此會員在商城加入時“會員編號”對錯]
處理方式：手動進商城會員資料庫修改對應資料
