### ISSUE TITLE
[阿原] POS-使用掃描槍有些活動無法帶入

### ISSUE THREAD

**Issue by kiwi-tcliu** [ringo636/Tib#658]
**[優先度]**  中高
**[環境]** windows,mac
**[瀏覽器]** chrome
**[重製率]** 100%
**[帳號]** 高雄駁二
**[異常說明]** 在設定任選件如果商品一個以上，會發生使用掃描槍無法帶入販促活動
**[結果]**
![2018-12-19 5 42 45](https://user-images.githubusercontent.com/44760867/50212665-8ca3ff80-03b6-11e9-8cab-b36ff3564a42.png)

> 此活動設定一個以上的活動會發生

![2018-12-19 5 51 13](https://user-images.githubusercontent.com/44760867/50212837-01773980-03b7-11e9-8c0b-e3fbb93188f0.png)

**[預期結果]**
應如圖，都帶入活動

**Comment by ringo636** [comment]
12/21上午已排除
原因主要是有部分商品在RMMS建立後刪除，
但因為刪除的商品資料在資料庫還是會有留存，造成程式判斷上的異常，
因此本次加上排除此狀況的程式碼以及優化國際條碼與料號的判斷方式
