### ISSUE TITLE
[阿原] POS-正式環境掃描商品，會出現"無法增加出售此商品"  (不算bug，就是個發現)

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#681]
環境: 正式
時間: 2018/12/20 19:54
重製率: 5/5 
瀏覽器: chrome
狀況說明:
[狀況a]
1. 游標沒有停留在任何地方
2. 掃描 喜心洛神

[狀況b]
1. 游標停留在商品搜尋框
2. 掃描 喜心洛神

[結果]
彈出無法增加出售此商品
[備註]
此商品是活動商品(買一送一)，但掃描一般商品也會這樣
只有在正式環境，demo環境不會

**Comment by ringo636** [comment]
12/21上午已解決此問題
原因同此issue https://github.com/ringo636/Tib/issues/658
