### ISSUE TITLE
[阿原] POS-正式環境用掃描掃 任選件的商品，無法帶入活動

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#682]
環境: 正式
時間: 2018/12/20
重製率: 5/5
商品名稱: 盈心苦瓜、古樹紅茶
狀況說明:
用掃描器掃描該商品
[結果] 不會帶入買一送一的活動價格，用手觸控螢幕就會顯示買一送一活動價格

[備註]
這個狀況在demo環境不會發生，只有在正式才會，掃描部分商品不會帶入活動價

**Comment by ringo636** [comment]
與 #658 同問題
