### ISSUE TITLE
[阿原] (demo)RMMS-匯入發票字軌(用範本檔案)，發票類別欄位預覽時亂碼

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#699]
環境: demo
瀏覽器: firefox
重製率: 5/5
帳號: olivia的帳號
狀況說明:
1. 匯入商城的字軌
2. 匯入檔案，按下預覽

[結果] 發票類別顯示亂碼
[備註] 需要匯入的檔案，在跟olivia說

![default](https://user-images.githubusercontent.com/42991376/50372893-89588000-0611-11e9-828e-1cc3006ef14e.png)

**Comment by kiwi-tcliu** [comment]
同#707，故關閉
