### ISSUE TITLE
[阿原] (demo)商城-增加商品後，購物車列表格式顯示是 「數量x總金額」

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#703]
環境: demo
瀏覽器: firefox
重製率: 5/5
狀況說明:
1. 增加一個商品，單價$560
2. 買5個，金額為$2800
[結果] 右側購物車列，顯示 [數量x總金額]
![default](https://user-images.githubusercontent.com/42991376/50375740-7a87c280-063d-11e9-81bb-132006e921c8.png)

[預期結果] 數量x單價 = 總金額

**Comment by alen-li** [comment]
已調整。

**Comment by ringo636** [comment]
已確認1/10上版完成
