### ISSUE TITLE
【泰國】完成周邊機器的手冊

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#72]
需求:
完成周邊機器的手冊(中文/英文)

備註:
周邊機器手冊已完成如附件
T810發票機安裝手冊
https://docs.google.com/document/d/1VI1AvS_182WnhAsRJhM_-dOCJbG7ycpxrGNRA-67pSM/edit?usp=sharing
標籤機安裝手冊
https://docs.google.com/document/d/1ZKmzFp5LlR_0Iq8bq1efN6texpWSvtE_1a7DS_wVKFI/edit?usp=sharing

**Comment by minzyliu** [comment]
預計需完成日期:2018/9/19

**Comment by minzyliu** [comment]
@alen-li  更換發票抬頭的補充說明與步驟，要再請你幫忙補充

**Comment by ringo636** [comment]
安裝標籤機步驟英文版
https://docs.google.com/document/d/19U7I94x1x4y5u8yZkW0AZZr8VBFgr0LJBeQWceaLwY8/edit?usp=sharing
