### ISSUE TITLE
[阿原] POS - 換貨後再退貨，帶進來的品項不是只有負的，而是一正一負

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#737]

**Comment by alen-li** [comment]
以更新至DEMO環境。

**Comment by ringo636** [comment]
狀況說明：
換貨後再退貨，會將正負品項都帶入，
在1/2修改了以後，發現會影響針對換貨單的退單金額會是原單與換貨單金額的加總，
所以1/9再麻煩阿華將此修改改回成換貨再退貨後還是帶入一正一負的品項
