### ISSUE TITLE
[阿原] (demo) - POS - 訂單demo_501和demo_502結帳後在今日銷售不會出現，但在RMMS查詢銷貨單是有建立成功的

### ISSUE THREAD

**Issue by ringo636** [ringo636/Tib#779]
環境: demo
瀏覽器: chrome
重製率: 5/5
帳號: yuansoap3
問題描述:
在測試機上使用 yuansoap3 登入 POS，
在1/2測試的訂單499跟500在 POS 的今日銷售查詢都會正常出現，但從1/3開始結帳的501跟502都不會在今日銷售出現，怎麼設查詢條件都不會出現，但上傳訂單後在RMMS查詢是有成功建立的，
請在幫忙確認，謝謝！

**Comment by alen-li** [comment]
經查是有看到的，此單增加時間在凌晨所以請注意跨日問題。

**Comment by ringo636** [comment]
好的，確認應是跨日問題，感謝～～
