### ISSUE TITLE
【泰國】POS翻譯更正

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#79]
需求:
部分的泰文翻譯須更正
[thai ตอบบบบบบบบบ.pptx](https://github.com/ringo636/Tib/files/2387281/thai.pptx)

**Comment by alen-li** [comment]
配合調整，but 第二頁的黃色框框是有甚麼特別含意嗎?

**Comment by minzyliu** [comment]
DONE
@alen-li  PAGE2的黃色框框，經過確認，泰國表示有破版
已請泰國提供較短的文字描述。
