### ISSUE TITLE
【POS】我的銷售中，把下方小計那行置頂

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#92]
需求:
POS我的銷售，小計/議價/總計/稅額的那行
1.移置上方(可參考下圖標示的位置)
2.文字放大
![default](https://user-images.githubusercontent.com/42991376/46062630-fd16f800-c19c-11e8-81a6-0f83268f47e5.PNG)

**Comment by ringo636** [comment]
在新版POS已修改
![2018-11-12 1 39 43](https://user-images.githubusercontent.com/6264391/48328751-718bf480-e680-11e8-9418-daff53abb339.png)
