### ISSUE TITLE
【泰國】泰國POS畫面，數字鍵盤加上小數點的按鈕

### ISSUE THREAD

**Issue by minzyliu** [ringo636/Tib#97]
需求:
POS的數字鍵盤加上小數點

備註:
以下兩種方法可擇一，或有其他方法可自行決定
(1) 在清除&箭頭按鈕下方在加一行按鈕
(2) 清除按鈕移除，改成小數點按鈕

**Comment by ringo636** [comment]
已變更為以下樣式：
![2018-09-28 9 59 25](https://user-images.githubusercontent.com/6264391/46183839-5d28ae00-c305-11e8-966a-c44e91a9ec11.png)
並已 commit 上 svn ，再麻煩 @alen-li 幫忙處理

**Comment by minzyliu** [comment]
done
